name: speedometer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  path_provider: ^2.1.4
  sensors_plus: ^6.0.1
  share_plus: ^10.0.3
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
